server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/station}
    username: ${DATABASE_USER:station}
    password: ${DATABASE_PASSWORD:anna}
    tomcat:
      initial-size: 5
      max-wait: 20000
      max-active: 9
      max-idle: 5
      min-idle: 7
      default-auto-commit: true
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
okta:
  oauth2:
    issuer: ${OKTA_OAUTH2_ISSUER:}
    client-id: ${OKTA_OAUTH2_CLIENT_ID_WEB:}
    client-secret: ${OKTA_OAUTH2_CLIENT_SECRET_WEB:}
    post-logout-redirect-uri: ${BASE_URL:localhost:8080}/logout/callback
