spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mariadb://localhost:3306/station}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
okta:
  oauth2:
    issuer: ${OKTA_OAUTH2_ISSUER}
    client-id: ${OKTA_OAUTH2_CLIENT_ID_WEB}
    client-secret: ${OKTA_OAUTH2_CLIENT_SECRET_WEB}
    post-logout-redirect-uri: ${BASE_URL}/logout/callback
    scopes: api openid
